builds:
  - main: ./cmd/kustomizer
    ldflags:
      - -s -w -X main.VERSION={{ .Version }}
    binary: kustomizer
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
brews:
  - tap:
      owner: stefanprodan
      name: kustomizer

    folder: Formula
    homepage: "https://kustomizer.dev/"
    description: "Kustomize build, apply, prune command-line utility."

    dependencies:
      - name: kubectl
        type: optional

    test: |
      system "#{bin}/kustomizer --version"