name: action-test

on:
  push:
    branches:
      - '*'

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Kustomizer
        uses: ./action
      - name: Run Kustomizer
        run: |
          kustomizer -v
