name: e2e

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
      - name: Run test
        run: make test
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Build
        run: make build
      - name: Apply test
        run: |
          ./bin/kustomizer apply -i kustomizer-demo -f testdata/plain/ --wait --prune
          kubectl -n kustomizer-demo get svc frontend 2>&1 | grep frontend
      - name: Prune test
        run: |
          rm -rf testdata/plain/frontend
          ./bin/kustomizer apply -i kustomizer-demo -f testdata/plain/ --wait --prune
          kubectl -n kustomizer-demo get svc frontend 2>&1 | grep NotFound
      - name: Delete test
        run: |
          ./bin/kustomizer delete -f testdata/plain/ --wait
          kubectl get ns kustomizer-demo 2>&1 | grep NotFound
      - name: Debug failure
        if: failure()
        run: |
          kubectl version --client --short
          kubectl -n default get configmaps -oyaml
          kubectl -n kustomizer-demo get all
